# Generated by Django 3.1 on 2020-12-31 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfStudy', models.CharField(max_length=30)),
                ('wantChazara', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Masechet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masechet_name', models.TextField(max_length=60)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.studyplan')),
            ],
        ),
        migrations.CreateModel(
            name='DafLearned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('is_learned', models.BooleanField(default=False)),
                ('chazara', models.IntegerField()),
                ('masechet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningapp.masechet')),
            ],
        ),
    ]
