# Generated by Django 3.1 on 2021-01-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0002_remove_daflearned_is_learned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masechet',
            name='masechet_name',
            field=models.CharField(max_length=60),
        ),
    ]
