# Generated by Django 3.1 on 2021-01-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0003_auto_20210110_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daflearned',
            name='masechet',
        ),
        migrations.AddField(
            model_name='daflearned',
            name='masechet_name',
            field=models.CharField(default='null', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daflearned',
            name='study_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='learningapp.studyplan'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Masechet',
        ),
    ]
