# Generated by Django 3.1 on 2021-01-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0004_auto_20210126_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daflearned',
            name='chazara',
            field=models.IntegerField(default=0),
        ),
    ]
