# Generated by Django 3.1 on 2021-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0005_auto_20210127_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
