# Generated by Django 3.1 on 2021-01-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0007_daflearned_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daflearned',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
