# Generated by Django 3.1 on 2021-02-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0008_auto_20210127_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='daflearned',
            name='index_in_list_dafs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
